//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IK_NEWEntities : DbContext
    {
        private static IK_NEWEntities _cotext;

        public IK_NEWEntities()
            : base("name=IK_NEWEntities")
        {
        }

        public static IK_NEWEntities GetContext()
        {
            if (_cotext == null)
                _cotext = new IK_NEWEntities();

            return _cotext;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
