//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public Nullable<int> Номер_инвертарной_книги { get; set; }
        public int Инвертарный_номер { get; set; }
        public string Автор { get; set; }
        public string Название { get; set; }
        public string Сведения_об_ответсвенности { get; set; }
        public string Сведения_об_издании { get; set; }
        public string Сведения_о_серии_или_многочастном_ресурсе { get; set; }
        public string Примечание_содержания { get; set; }
        public string Раздел_систематического_каталога { get; set; }
        public string Место_издания { get; set; }
        public string Имя_издателя { get; set; }
        public Nullable<System.DateTime> Год_издания { get; set; }
        public Nullable<bool> Отметки_о_выбытии { get; set; }
        public string Примичание { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Примичание_по_Большаковой { get; set; }
    }
}
